name: birdcloud
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - h5py
  - jupyter
  - jupyterlab
  - wradlib
  - numpy
  - pytest
  - scipy
  - pandas
  - docker-py
  - xarray
  - python=3.7.2